# This Appveyor configuration file is modified from Stack's documentation
#   https://github.com/commercialhaskell/stack/blob/stable/doc/appveyor.yml
#
# A discussion is available here:
#   https://www.snoyman.com/blog/2016/08/appveyor-haskell-windows-ci
#
build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

# Miniconda is preinstalled on Appveyor images
# https://www.appveyor.com/docs/windows-images-software/#python
- "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
- conda update --yes -n base conda

- "conda --version"
- "python --version"

cache: 
  - "C:\\sr"


# Skipping commits affecting specific files (GitHub only).
# More details here: /docs/appveyor-yml
skip_commits:
  files:
    - examples/*
    - '*.md'
    - azure-pipelines.yml
    - .azure/*

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: "c:\\tmp"

    MINICONDA: "C:\\Miniconda3-64"
    
  matrix:
  - ARGS: "--resolver lts-11"  # GHC 8.2
  - ARGS: "--resolver lts-12"  # GHC 8.4
  - ARGS: "--resolver lts-13"  # GHC 8.6
  - ARGS: "--resolver lts-14"  # GHC 8.6
  # - ARGS: "--resolver nightly"

matrix:
  fast_finish: true

test_script:

# Install toolchain, but do it silently due to lots of output
- stack %ARGS% setup > nul

# Pillow is required to save images to jpg
- conda install --yes matplotlib pillow

# Plotly installation instructions are more complex because we export static images
# https://plot.ly/python/static-image-export/
- conda install --yes -c plotly plotly-orca psutil requests
- conda install --yes plotly

# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack %ARGS% --no-terminal test --fast --ghc-options=-Werror

# Integration testing
# In the past, executables were built that misparsed input flags (see Issue #2)
# Therefore, we have some integration test that works on some test file
- echo "" | stack %ARGS% --no-terminal install . pandoc
- stack %ARGS% exec -- pandoc --filter pandoc-pyplot -i ./test/fixtures/integration.md -o ./generated/test.html
