# This Appveyor configuration file is modified from Stack's documentation
#   https://github.com/commercialhaskell/stack/blob/stable/doc/appveyor.yml
#
# A discussion is available here:
#   https://www.snoyman.com/blog/2016/08/appveyor-haskell-windows-ci
#
build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

cache: 
  - "C:\\sr"


# Skipping commits affecting specific files (GitHub only).
# More details here: /docs/appveyor-yml
skip_commits:
  files:
    - examples/*
    - '*.md'

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: "c:\\tmp"

  matrix:
  - ARGS: "--resolver lts-12"
  - ARGS: "--resolver lts-13"
  - ARGS: "--resolver nightly"

matrix:
  fast_finish: true

test_script:

# Install toolchain, but do it silently due to lots of output
- stack %ARGS% setup > nul

# Python is preinstalled on Appveyor images
# https://www.appveyor.com/docs/windows-images-software/#python
# The default is unfortunately Python 2.7
# Note that pillow is required to save images to jpg
- python -m pip install --upgrade matplotlib 
- python -m pip install --upgrade pillow

# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack %ARGS% --no-terminal test --ghc-options=-Werror